# Generated by Django 4.2.5 on 2025-04-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_api', 'xxxx_add_fan_anomaly_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmetric',
            options={'ordering': ['-timestamp'], 'verbose_name': 'System Metric', 'verbose_name_plural': 'System Metrics'},
        ),
        migrations.RemoveIndex(
            model_name='systemmetric',
            name='hardware_ap_timesta_c913d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemmetric',
            name='hardware_ap_is_anom_f79023_idx',
        ),
        migrations.RemoveField(
            model_name='systemmetric',
            name='disk_read_count',
        ),
        migrations.RemoveField(
            model_name='systemmetric',
            name='disk_write_count',
        ),
        migrations.RemoveField(
            model_name='systemmetric',
            name='fan_rpm_max',
        ),
        migrations.RemoveField(
            model_name='systemmetric',
            name='fan_rpm_min',
        ),
        migrations.RemoveField(
            model_name='systemmetric',
            name='swap_percent',
        ),
        migrations.AddField(
            model_name='hardwareissue',
            name='fan_anomaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hardwareissue',
            name='fan_expected_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hardwareissue',
            name='fan_rpm_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hardwareissue',
            name='fan_rpm_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemmetric',
            name='anomaly_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='systemmetric',
            name='battery_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='systemmetric',
            name='cpu_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='systemmetric',
            name='cpu_temp',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='systemmetric',
            name='disk_usage_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='systemmetric',
            name='fan_expected_speed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='systemmetric',
            name='fan_speed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='systemmetric',
            name='memory_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='systemmetric',
            name='network_bytes_recv',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='systemmetric',
            name='network_bytes_sent',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='systemmetric',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
