# Generated by Django 4.2.5 on 2025-04-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_api', '0001_alter_systemmetric_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetric',
            name='disk_read_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='systemmetric',
            name='disk_write_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='systemmetric',
            name='swap_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
